import 'dart:io';

import 'package:args/args.dart';
import 'package:path/path.dart' as p;

import '../checker/layer_validator.dart';
import '../graph/dependency_graph.dart';
import '../models/config_model.dart';
import '../models/layer_presets.dart';
import '../scanner/layout_detector.dart';
import '../scanner/project_scanner.dart';

/// Default ignore patterns written by `arch_guard init`.
const _defaultIgnores = [
  '**/*.g.dart',
  '**/*.freezed.dart',
  '**/*.mocks.dart',
  '**/*.gr.dart',
  '**/*.config.dart',
];

/// Runs `arch_guard init`: detects the project layout, writes a starter
/// `arch_guard.yaml` and previews what the first scan finds.
Future<int> runInit(ArgResults args) async {
  final projectPath = args.rest.isNotEmpty ? args.rest.first : '.';
  final absProjectPath = p.canonicalize(projectPath);
  if (!Directory(absProjectPath).existsSync()) {
    stderr.writeln(
      'Error: Project directory "$absProjectPath" does not exist.',
    );
    return 2;
  }

  final configFile = File(p.join(absProjectPath, 'arch_guard.yaml'));
  final dryRun = args['dry-run'] as bool;
  if (configFile.existsSync() && !(args['force'] as bool) && !dryRun) {
    stderr.writeln(
      'Error: ${configFile.path} already exists. Use --force to overwrite it, '
      'or --dry-run to preview a new one.',
    );
    return 1;
  }

  final requested = args['preset'] as String;
  final LayoutDetection detection;
  if (requested == 'auto') {
    detection = LayoutDetector.detect(absProjectPath);
  } else if (requested == 'none') {
    detection = const LayoutDetection(null, 'requested with --preset none');
  } else {
    detection = LayoutDetection(requested, 'requested with --preset');
  }

  final yaml = buildInitConfig(
    preset: detection.preset,
    reason: detection.reason,
    rootPath: absProjectPath,
  );

  if (dryRun) {
    stdout.write(yaml);
    stdout.writeln();
  } else {
    configFile.writeAsStringSync(yaml);
    stdout.writeln(
      'Created ${_display(configFile.path)} '
      '(${detection.preset != null ? 'preset: ${detection.preset}' : 'no preset'}'
      '; ${detection.reason}).',
    );
  }

  if (_pubspecHasConfig(absProjectPath)) {
    stdout.writeln(
      'Note: pubspec.yaml has an `arch_guard:` section; arch_guard.yaml takes '
      'priority over it.',
    );
  }

  final config = ArchGuardConfig.parse(yaml, rootPath: absProjectPath);
  for (final warning in config.warnings) {
    stderr.writeln('Warning: $warning');
  }
  await _preview(absProjectPath, config);
  return 0;
}

/// Builds the starter configuration text for `arch_guard init`.
String buildInitConfig({
  required String? preset,
  required String reason,
  required String rootPath,
}) {
  final b = StringBuffer()
    ..writeln('# arch_guard.yaml, generated by `arch_guard init`.')
    ..writeln('# Layout: $reason.')
    ..writeln(
      '# Reference: https://github.com/creatorpiyush/arch_guard'
      '#configuration-arch_guardyaml-or-pubspecyaml',
    )
    ..writeln();

  if (preset != null) {
    final layers = LayerPresets.expand(preset, rootPath: rootPath) ?? {};
    b
      ..writeln('# ${LayerPresets.descriptions[preset]}')
      ..writeln('preset: $preset')
      ..writeln()
      ..writeln('# The preset expands to the layers below. To change a layer,')
      ..writeln('# list it under `layers:` with just the keys to change (e.g.')
      ..writeln('# `allowed_imports`); new layer names are added.');
    if (preset == LayerPresets.featureFirst) {
      b.writeln(
        '# Feature layers are rediscovered from the folders on every run.',
      );
    }
    b.writeln('#');
    b.writeln('# layers:');
    for (final layer in layers.values) {
      b
        ..writeln('#   ${layer.name}:')
        ..writeln('#     patterns: [${layer.patterns.map(_quote).join(', ')}]')
        ..writeln(
          '#     allowed_imports: [${layer.allowedImports.join(', ')}]',
        );
    }
  } else {
    b
      ..writeln('# No preset matched. Pick one of:')
      ..writeln('#   preset: ${LayerPresets.names.join(' | ')}')
      ..writeln('# or describe your layers. Each layer lists the layers it may')
      ..writeln(
        '# import; a file belongs to the first layer whose pattern matches.',
      )
      ..writeln('#')
      ..writeln('# layers:')
      ..writeln('#   domain:')
      ..writeln('#     patterns: ["lib/domain/**"]')
      ..writeln('#     allowed_imports: [domain]')
      ..writeln('#   presentation:')
      ..writeln('#     patterns: ["lib/presentation/**"]')
      ..writeln('#     allowed_imports: [presentation, domain]');
  }

  b
    ..writeln()
    ..writeln('ignore:');
  for (final pattern in _defaultIgnores) {
    b.writeln('  - ${_quote(pattern)}');
  }
  b
    ..writeln()
    ..writeln('fail_on_layer_violation: true')
    ..writeln()
    ..writeln('# Fail when a circular-dependency group grows beyond N files:')
    ..writeln('# max_scc_size: 10');
  return b.toString();
}

String _quote(String s) => '"$s"';

/// [path] relative to the working directory when inside it, else absolute.
String _display(String path) {
  final rel = p.relative(path);
  return rel.startsWith('..') ? path : rel;
}

bool _pubspecHasConfig(String root) {
  final pubspec = File(p.join(root, 'pubspec.yaml'));
  return pubspec.existsSync() &&
      RegExp(
        r'^arch_guard\s*:',
        multiLine: true,
      ).hasMatch(pubspec.readAsStringSync());
}

/// Scans the project with [config] and prints how files fall into layers and
/// how many problems exist, with the suggested next step.
Future<void> _preview(String root, ArchGuardConfig config) async {
  final scan = await ProjectScanner(
    rootPath: root,
    exclude: config.ignorePatterns,
  ).scan();
  final cycles = DependencyGraph.fromScanResult(
    scan,
  ).findCircularDependencies();
  final violations = LayerValidator.validate(result: scan, config: config);

  stdout.writeln();
  stdout.writeln('First scan: ${scan.files.length} files');
  if (config.layers.isNotEmpty) {
    final coverage = LayerValidator.coverage(result: scan, config: config);
    final width = [
      ...config.layers.keys,
      '(no layer)',
    ].fold<int>(0, (w, n) => n.length > w ? n.length : w);
    coverage.layerFileCounts.forEach((layer, count) {
      stdout.writeln('  ${layer.padRight(width)}  $count file(s)');
    });
    if (coverage.unassignedFiles.isNotEmpty) {
      stdout.writeln(
        '  ${'(no layer)'.padRight(width)}  '
        '${coverage.unassignedFiles.length} file(s), not checked',
      );
    }
  }
  stdout.writeln(
    '  ${violations.length} layer violation(s), '
    '${cycles.length} circular dependency group(s)',
  );
  stdout.writeln();

  if (violations.isEmpty && cycles.isEmpty) {
    stdout.writeln('Next: add `arch_guard` to CI to keep it that way.');
  } else {
    stdout.writeln(
      'Next: run `arch_guard` for details, or `arch_guard --update-baseline` '
      'to accept the current problems and fail only on new ones.',
    );
  }
}
